export const districts = [
  {
    id: 'projects',
    index: '01',
    name: 'Cidade de Dados',
    short: 'Projetos',
    subtitle: 'Projetos orientados a negócio',
    description:
      'Cases de SQL, dashboards executivos, atribuição de marketing, testes A/B e relatórios setoriais. Ideal para destacar profundidade analítica e entrega.',
    color: '#5eead4',
    accent: '#14b8a6',
    position: [-10, 0, 5],
    size: [5, 8, 5],
    details: [
      'Projeto completo de SQL com insights',
      'Comparação de modelos de atribuição',
      'Painéis orientados por pergunta de negócio',
      'Análises estatísticas e storytelling executivo',
    ],
  },
  {
    id: 'about',
    index: '02',
    name: 'Casa do Analista',
    short: 'Sobre Mim',
    subtitle: 'Trajetória, foco e posicionamento',
    description:
      'Seção institucional para apresentar perfil, experiência, contexto profissional e diferenciais como analista com visão de negócio e execução.',
    color: '#f59e0b',
    accent: '#ea580c',
    position: [-4, 0, -7],
    size: [4.5, 4.2, 4.5],
    details: [
      'Resumo executivo',
      'Histórico profissional e estudos',
      'Posicionamento em BI, SQL e produto de dados',
      'Diferenciais práticos e visão operacional',
    ],
  },
  {
    id: 'stack',
    index: '03',
    name: 'Laboratório Tech',
    short: 'Stack',
    subtitle: 'Linguagens e ferramentas',
    description:
      'Ambiente para exibir stack técnica, frameworks, bancos de dados e ferramentas analíticas. Útil para mostrar capacidade de implementação além da análise.',
    color: '#60a5fa',
    accent: '#2563eb',
    position: [3.5, 0, 7],
    size: [5, 5.5, 5],
    details: ['SQL', 'Python', 'Power BI', 'Excel', 'React', 'Node.js', 'MySQL'],
  },
  {
    id: 'dashboards',
    index: '04',
    name: 'Torre de Insights',
    short: 'Dashboards',
    subtitle: 'KPIs, análises e visualização',
    description:
      'Prédio principal para painéis analíticos. A proposta é destacar dashboards executivos, drill-down, tendências e leitura de performance.',
    color: '#a78bfa',
    accent: '#7c3aed',
    position: [10, 0, -3],
    size: [4.2, 11, 4.2],
    details: [
      'Dashboards executivos',
      'KPIs e séries temporais',
      'Mapas e análises geográficas',
      'Causa raiz e decomposição',
    ],
  },
  {
    id: 'contact',
    index: '05',
    name: 'Estação de Contato',
    short: 'Contato',
    subtitle: 'GitHub, LinkedIn e currículo',
    description:
      'Hub institucional com canais de contato, links profissionais e currículo. Fecha a experiência com um CTA claro para recrutadores e clientes.',
    color: '#fb7185',
    accent: '#e11d48',
    position: [0, 0, 13],
    size: [6, 3.2, 4.5],
    details: ['GitHub', 'LinkedIn', 'Currículo', 'E-mail profissional'],
  },
];
