export const DISTRICTS = {
  projetos: {
    id: 'projetos',
    name: 'Cidade de Dados',
    subtitle: 'Projetos',
    tag: 'PROJETOS',
    color: '#4f8cff',
    tagBg: 'rgba(79,140,255,.2)',
    pos: { x: 0, z: 0 },
    desc: 'Cases analíticos, SQL, marketing attribution, A/B tests e relatórios orientados por negócio.',
    items: [
      { icon: '🗃', title: 'SQL Analytics Engine', sub: 'Projeto completo com insights de negócio' },
      { icon: '📈', title: 'Marketing Attribution', sub: 'Comparação de modelos multi-touch' },
      { icon: '❓', title: 'Business Dashboard', sub: 'Painel que responde perguntas de negócio' },
      { icon: '🧪', title: 'A/B Test Analysis', sub: 'Análise estatística com significância' },
      { icon: '📋', title: 'Sector Report', sub: 'Relatório setorial orientado por dados' },
    ],
  },
  sobre: {
    id: 'sobre',
    name: 'Casa & Escritório',
    subtitle: 'Sobre Mim',
    tag: 'SOBRE MIM',
    color: '#06ffa5',
    tagBg: 'rgba(6,255,165,.15)',
    pos: { x: -28, z: -22 },
    desc: 'Analista de dados apaixonado por transformar dados em decisões estratégicas.',
    items: [
      { icon: '👤', title: 'Quem sou eu', sub: 'Analista de dados & storyteller' },
      { icon: '🎓', title: 'Formação', sub: 'Estatística · Ciência de Dados' },
      { icon: '💼', title: 'Experiência', sub: '3+ anos em analytics & BI' },
      { icon: '🌟', title: 'Especialidades', sub: 'SQL · Python · Visualização' },
      { icon: '🎯', title: 'Objetivo', sub: 'Insights que movem o negócio' },
    ],
  },
  laboratorio: {
    id: 'laboratorio',
    name: 'Laboratório Tech',
    subtitle: 'Linguagens & Ferramentas',
    tag: 'LABORATÓRIO',
    color: '#b97fff',
    tagBg: 'rgba(185,127,255,.15)',
    pos: { x: 28, z: -22 },
    desc: 'Ambiente de experimentação com linguagens, frameworks e ferramentas de dados.',
    items: [
      { icon: '🐍', title: 'Python', sub: 'Pandas · NumPy · Scikit-learn' },
      { icon: '🗄', title: 'SQL', sub: 'PostgreSQL · BigQuery · dbt' },
      { icon: '📊', title: 'BI Tools', sub: 'Power BI · Tableau · Looker' },
      { icon: '☁', title: 'Cloud', sub: 'GCP · AWS · Azure' },
      { icon: '🔧', title: 'DevTools', sub: 'Git · Docker · Airflow' },
    ],
  },
  dashboards: {
    id: 'dashboards',
    name: 'Torre de Insights',
    subtitle: 'Dashboards & Análises',
    tag: 'DASHBOARDS',
    color: '#ffd166',
    tagBg: 'rgba(255,209,102,.15)',
    pos: { x: 0, z: -44 },
    desc: 'Torre de análises avançadas: dashboards interativos, KPIs e storytelling visual.',
    items: [
      { icon: '📡', title: 'Executive Dashboard', sub: 'KPIs em tempo real para C-level' },
      { icon: '🔍', title: 'Cohort Analysis', sub: 'Retenção e churn por coorte' },
      { icon: '💡', title: 'Funnel Analytics', sub: 'Conversão e drop-off analysis' },
      { icon: '🗺', title: 'Geo Intelligence', sub: 'Análise geoespacial de mercado' },
      { icon: '⚡', title: 'Real-time KPIs', sub: 'Monitoramento contínuo de métricas' },
    ],
  },
  contato: {
    id: 'contato',
    name: 'Estação de Contato',
    subtitle: 'Conecte-se',
    tag: 'CONTATO',
    color: '#ff6b6b',
    tagBg: 'rgba(255,107,107,.15)',
    pos: { x: 0, z: 26 },
    desc: 'Hub de comunicação — LinkedIn, GitHub e currículo. Vamos trabalhar juntos.',
    links: [
      { icon: '💼', title: 'LinkedIn', url: 'linkedin.com/in/seu-perfil', href: '#' },
      { icon: '🐙', title: 'GitHub', url: 'github.com/seu-usuario', href: '#' },
      { icon: '📄', title: 'Currículo', url: 'Baixar PDF atualizado', href: '#' },
      { icon: '✉', title: 'E-mail', url: 'seuemail@exemplo.com', href: '#' },
    ],
  },
}

export const FLY_TARGETS = {
  projetos:    { tx: 0,   tz: 0,   radius: 30, phi: 0.50 },
  sobre:       { tx: -28, tz: -22, radius: 26, phi: 0.46 },
  laboratorio: { tx: 28,  tz: -22, radius: 26, phi: 0.46 },
  dashboards:  { tx: 0,   tz: -44, radius: 28, phi: 0.44 },
  contato:     { tx: 0,   tz: 26,  radius: 26, phi: 0.46 },
}
